### ISSUE TITLE
图标是阿里图标库修改颜色后下载的，在项目里通过setGlobalOption配置的颜色无效。

### ISSUE THREAD

**Issue by gaojianghua** [svg-in-js/svgjs#2]
![image](https://github.com/svg-in-js/svgjs/assets/61684763/73bb0a75-913b-4b71-89d1-d960bdcc0164)

**Comment by gaojianghua** [comment]
你有群吗？拉一个QQ讨论群吧

**Comment by famanoder** [comment]
目前只支持了对单色图标设置颜色，我看你上面那个图标是不是就有颜色了

**Comment by famanoder** [comment]
你先加我 qq 说吧，915905174

**Comment by gaojianghua** [comment]
真名叫啥？加你要回答问题

**Comment by gaojianghua** [comment]
或者你加我598670138

**Comment by famanoder** [comment]
ok
